name: saavnapi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.0.0
  dart_des: ^1.0.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
